.TH overview server

.SH NAME
server-overview - General information on the server libraries

.SH DESCRIPTION
Server.h is meant to be used as a library for files like leader.h and backup.h. Those files are more templates than anything so with just minor modification you can have a working server.

.SH EXPLANATION

First time a leader server starts it gets two threads. One for processing commands sent by other threads, other for connecting to new servers and 
.IR spawning more threads 
for each of them.

.B (the following parts aren't fully implemented yet)
As the leader process gets more servers it will give them ids and puts them in a list. After processing a request from the client, leader server just needs to redirect them to backup servers. 

Leader server recieves client server messages in a their own thread and we need them in backup servers' threads, so somehow we need to send data accross threads. The functions threadMsgSend() and threadMsgRecv() pretty much automate entire thing. Definetely check manpage sometime.

.SH NOTES
Current demo in main.c cancels the threads on exit. The server is setup to allow this but valgrind famously hates thread cancellation. For this reason threads are also detached just in case.

.SH MANPAGES
You will find user manual and programmers manual towards bottom of each function page. First one is for using the function and what to look out for etc while second one is for how it works.

